# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4184ed42-e140-4e05-af19-8691aae28ada'
  imageRepository: 'webappfastcom'
  containerRegistry: 'mutkukulregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscription: 'Free Trial(154b2920-a416-4985-9cdf-f9afa887a627)'
            azureContainerRegistry: '{"loginServer":"mutkukulregistry.azurecr.io", "id" : "/subscriptions/154b2920-a416-4985-9cdf-f9afa887a627/resourceGroups/MutkukulRegistry-dev-rg/providers/Microsoft.ContainerRegistry/registries/MutkukulRegistry"}'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Run a Docker Compose command'
            dockerComposeCommand: 'rm --all'
            nopIfNoDockerComposeFile: true